services:
  webserver:
    image: nginx:latest
    ports:
      - 8080:80
      - 8081:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d:ro,z
      - ./static/:/var/www/html:ro,z
      - ./ssl:/etc/ssl:ro,z
      - /data:/data:ro,z
