services:
  webserver:
    image: nginx:latest
    ports:
      - 8080:80
      - 8081:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d:ro,z,noexec
      - ./static/:/var/www/html:ro,z,noexec
      - ./ssl:/etc/ssl:ro,z,noexec
      - /data:/data:ro,noexec
    security_opt:
      label: disable
